// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using omsapi.Data;

#nullable disable

namespace omsapi.MigrationsPg
{
    [DbContext(typeof(OmsPgContext))]
    [Migration("20260105101512_InitialPgVector")]
    partial class InitialPgVector
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OmsApi.Models.Entities.Kb.KbFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Extension")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsFolder")
                        .HasColumnType("boolean");

                    b.Property<Guid>("KbId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UploadTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("KbId");

                    b.HasIndex("ParentId");

                    b.ToTable("kb_file");
                });

            modelBuilder.Entity("OmsApi.Models.Entities.Kb.KbInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("kb_info");
                });

            modelBuilder.Entity("OmsApi.Models.Entities.Kb.KbNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<Guid>("KbId")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("KbId");

                    b.HasIndex("ParentId");

                    b.ToTable("sys_kb_node", (string)null);
                });

            modelBuilder.Entity("OmsApi.Models.Entities.Kb.KbNodeSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Page")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.HasIndex("NodeId");

                    b.ToTable("kb_node_source");
                });

            modelBuilder.Entity("OmsApi.Models.Entities.Kb.KbFile", b =>
                {
                    b.HasOne("OmsApi.Models.Entities.Kb.KbInfo", "Kb")
                        .WithMany("Files")
                        .HasForeignKey("KbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmsApi.Models.Entities.Kb.KbFile", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Kb");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("OmsApi.Models.Entities.Kb.KbNode", b =>
                {
                    b.HasOne("OmsApi.Models.Entities.Kb.KbInfo", "Kb")
                        .WithMany("Nodes")
                        .HasForeignKey("KbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmsApi.Models.Entities.Kb.KbNode", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Kb");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("OmsApi.Models.Entities.Kb.KbNodeSource", b =>
                {
                    b.HasOne("OmsApi.Models.Entities.Kb.KbFile", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmsApi.Models.Entities.Kb.KbNode", "Node")
                        .WithMany("Sources")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("Node");
                });

            modelBuilder.Entity("OmsApi.Models.Entities.Kb.KbInfo", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("OmsApi.Models.Entities.Kb.KbNode", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Sources");
                });
#pragma warning restore 612, 618
        }
    }
}
