using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using omsapi.Data;
using omsapi.Models.Entities.System;
using omsapi.Services.Interfaces;
using omsapi.Infrastructure.Attributes;
using System.Data.Common;
using Microsoft.Extensions.Configuration;

namespace omsapi.Services
{
    [AutoInject(ServiceLifetime.Scoped)]
    public class SqlMigrationService : ISqlMigrationService
    {
        private readonly OmsContext _context;
        private readonly ILogger<SqlMigrationService> _logger;
        private readonly string _migrationPath;

        public SqlMigrationService(OmsContext context, ILogger<SqlMigrationService> logger, IConfiguration configuration)
        {
            _context = context;
            _logger = logger;
            // Path relative to the application base directory (where the app runs)
            var root = Path.Combine(AppContext.BaseDirectory, "database");
            var dbType = (configuration["DatabaseType"] ?? "mysql").ToLowerInvariant();
            var subdir = dbType switch
            {
                "sqlserver" => "mssql",
                "mssql" => "mssql",
                "postgres" => "postgresql",
                "postgresql" => "postgresql",
                _ => "mysql"
            };
            _migrationPath = Path.Combine(root, subdir);
            _logger.LogInformation($"SQL 迁移路径解析为: {_migrationPath} (数据库类型={dbType})");
        }

        public async Task ApplyMigrationsAsync()
        {
            try
            {
                // 1. Ensure the tracking table exists
                await EnsureMigrationTableExistsAsync();

                // 2. Get executed migrations
                var executedFiles = await _context.DbMigrations
                    .Select(m => m.FileName)
                    .ToListAsync();

                // 3. Scan for .sql files
                if (!Directory.Exists(_migrationPath))
                {
                    _logger.LogWarning($"Migration directory not found: {_migrationPath}");
                    return;
                }

                var files = Directory.GetFiles(_migrationPath, "*.sql")
                    .Select(Path.GetFileName)
                    .OrderBy(f => f) // Ensure deterministic order (e.g. 001, 002)
                    .ToList();

                foreach (var file in files)
                {
                    if (file == null) continue;
                    
                    if (executedFiles.Contains(file))
                    {
                        continue;
                    }

                    await ExecuteMigrationAsync(file);
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed to apply SQL migrations");
                throw;
            }
        }

        private async Task EnsureMigrationTableExistsAsync()
        {
            var exists = false;
            try
            {
                // Try to query the table to see if it exists
                await _context.DbMigrations.AnyAsync();
                exists = true;
            }
            catch
            {
                // Table likely doesn't exist
                exists = false;
            }

            if (!exists)
            {
                _logger.LogInformation("Creating sys_db_migration table...");
                
                // Determine DB provider to generate correct SQL
                var provider = _context.Database.ProviderName;
                string createSql;

                if (provider != null && provider.Contains("SqlServer"))
                {
                     createSql = @"
                        IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='sys_db_migration' AND xtype='U')
                        CREATE TABLE sys_db_migration (
                            Id BIGINT IDENTITY(1,1) PRIMARY KEY,
                            FileName NVARCHAR(255) NOT NULL,
                            ExecutedAt DATETIME NOT NULL,
                            Status NVARCHAR(50) DEFAULT 'success',
                            ErrorMessage NVARCHAR(MAX) NULL
                        );";
                }
                else if (provider != null && provider.Contains("PostgreSQL"))
                {
                     createSql = @"
                        CREATE TABLE IF NOT EXISTS sys_db_migration (
                            ""Id"" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            ""FileName"" VARCHAR(255) NOT NULL,
                            ""ExecutedAt"" TIMESTAMP NOT NULL,
                            ""Status"" VARCHAR(50) DEFAULT 'success',
                            ""ErrorMessage"" TEXT NULL
                        );";
                }
                else // MySQL default
                {
                    createSql = @"
                        CREATE TABLE IF NOT EXISTS sys_db_migration (
                            Id BIGINT AUTO_INCREMENT PRIMARY KEY,
                            FileName VARCHAR(255) NOT NULL,
                            ExecutedAt DATETIME NOT NULL,
                            Status VARCHAR(50) DEFAULT 'success',
                            ErrorMessage LONGTEXT
                        );";
                }

                await _context.Database.ExecuteSqlRawAsync(createSql);
            }
        }

        private async Task ExecuteMigrationAsync(string fileName)
        {
            _logger.LogInformation($"Executing migration: {fileName}");
            var filePath = Path.Combine(_migrationPath, fileName);
            var content = await File.ReadAllTextAsync(filePath);
            var provider = _context.Database.ProviderName ?? string.Empty;

            var migrationRecord = new SysDbMigration
            {
                FileName = fileName,
                ExecutedAt = DateTime.Now,
                Status = "pending"
            };

            var strategy = _context.Database.CreateExecutionStrategy();

            await strategy.ExecuteAsync(async () =>
            {
                try
                {
                    // Execute the SQL script by splitting into individual statements
                    var statements = SplitSqlStatements(content);

                    var connection = _context.Database.GetDbConnection();
                    if (connection.State != System.Data.ConnectionState.Open)
                    {
                        await connection.OpenAsync();
                    }

                    if (provider.Contains("MySql"))
                    {
                        foreach (var stmt in statements)
                        {
                            if (string.IsNullOrWhiteSpace(stmt)) continue;
                            using var cmd = connection.CreateCommand();
                            cmd.CommandText = stmt;
                            cmd.CommandType = System.Data.CommandType.Text;
                            await cmd.ExecuteNonQueryAsync();
                        }
                    }
                    else
                    {
                        using var transaction = await _context.Database.BeginTransactionAsync();
                        foreach (var stmt in statements)
                        {
                            if (string.IsNullOrWhiteSpace(stmt)) continue;
                            using var cmd = connection.CreateCommand();
                            cmd.Transaction = (DbTransaction?)_context.Database.CurrentTransaction?.GetDbTransaction();
                            cmd.CommandText = stmt;
                            cmd.CommandType = System.Data.CommandType.Text;
                            await cmd.ExecuteNonQueryAsync();
                        }
                        await transaction.CommitAsync();
                    }

                    // Save the record
                    migrationRecord.Status = "success";
                    _context.DbMigrations.Add(migrationRecord);
                    await _context.SaveChangesAsync();

                    _logger.LogInformation($"Successfully executed migration: {fileName}");
                }
                catch (Exception ex)
                {
                    _logger.LogError(ex, $"Error executing migration {fileName}");
                    
                    // We might want to record the failure? 
                    // But if we rollback, we can't save the record in the same transaction.
                    // For now, we just let it fail and bubble up, so it will be retried on next restart (or fixed manually).
                    throw; 
                }
            });
        }

        // Split multi-statement SQL into individual statements, respecting quotes and comments
        private static List<string> SplitSqlStatements(string sql)
        {
            var result = new List<string>();
            var sb = new System.Text.StringBuilder();
            bool inSingleQuote = false;
            bool inDoubleQuote = false;
            bool inBacktick = false;
            bool inLineComment = false;   // --
            bool inBlockComment = false;  // /* ... */

            for (int i = 0; i < sql.Length; i++)
            {
                char c = sql[i];
                char next = i + 1 < sql.Length ? sql[i + 1] : '\0';

                if (!inSingleQuote && !inDoubleQuote && !inBacktick)
                {
                    // Handle comments
                    if (!inBlockComment && !inLineComment && c == '-' && next == '-')
                    {
                        inLineComment = true;
                    }
                    else if (!inBlockComment && !inLineComment && c == '/' && next == '*')
                    {
                        inBlockComment = true;
                    }
                    else if (inLineComment && (c == '\r' || c == '\n'))
                    {
                        inLineComment = false;
                    }
                    else if (inBlockComment && c == '*' && next == '/')
                    {
                        inBlockComment = false;
                        i++; // skip '/'
                        continue;
                    }

                    if (inLineComment || inBlockComment)
                    {
                        // Skip comment characters
                        continue;
                    }
                }

                // Track quote states
                if (!inLineComment && !inBlockComment)
                {
                    if (!inDoubleQuote && !inBacktick && c == '\'' && !IsEscaped(sql, i))
                        inSingleQuote = !inSingleQuote;
                    else if (!inSingleQuote && !inBacktick && c == '\"' && !IsEscaped(sql, i))
                        inDoubleQuote = !inDoubleQuote;
                    else if (!inSingleQuote && !inDoubleQuote && c == '`')
                        inBacktick = !inBacktick;
                }

                if (c == ';' && !inSingleQuote && !inDoubleQuote && !inBacktick && !inLineComment && !inBlockComment)
                {
                    var stmt = sb.ToString().Trim();
                    if (!string.IsNullOrWhiteSpace(stmt))
                        result.Add(stmt);
                    sb.Clear();
                }
                else
                {
                    sb.Append(c);
                }
            }

            var last = sb.ToString().Trim();
            if (!string.IsNullOrWhiteSpace(last))
                result.Add(last);

            return result;
        }

        private static bool IsEscaped(string s, int index)
        {
            int backslashes = 0;
            for (int i = index - 1; i >= 0 && s[i] == '\\'; i--)
                backslashes++;
            return backslashes % 2 == 1;
        }
    }
}
