-- Add Chinese Comments to All Tables
ALTER TABLE `api_category` COMMENT = 'API分类';
ALTER TABLE `api_category` MODIFY COLUMN `Id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `api_definition` COMMENT = 'API定义';
ALTER TABLE `api_definition` MODIFY COLUMN `Id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `arch_attachment` COMMENT = '档案附件';
ALTER TABLE `arch_attachment` MODIFY COLUMN `Id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `arch_box` COMMENT = '档案盒';
ALTER TABLE `arch_box` MODIFY COLUMN `Id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `arch_file` COMMENT = '档案文件';
ALTER TABLE `arch_file` MODIFY COLUMN `Id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `arch_fond` COMMENT = '全宗';
ALTER TABLE `arch_fond` MODIFY COLUMN `Id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `arch_type` COMMENT = '档案类型';
ALTER TABLE `arch_type` MODIFY COLUMN `Id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `arch_type` MODIFY COLUMN `ParentId` bigint NULL DEFAULT NULL COMMENT '父级ID';
ALTER TABLE `contract_attachment` COMMENT = '合同附件';
ALTER TABLE `contract_attachment` MODIFY COLUMN `Id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `contract_contact` COMMENT = '合同联系人';
ALTER TABLE `contract_contact` MODIFY COLUMN `Id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `contract_invoice` COMMENT = '合同发票';
ALTER TABLE `contract_invoice` MODIFY COLUMN `Id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `contract_knowledge_category` COMMENT = '合同知识分类';
ALTER TABLE `contract_knowledge_category` MODIFY COLUMN `Id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `contract_knowledge_file` COMMENT = '合同知识文件';
ALTER TABLE `contract_knowledge_file` MODIFY COLUMN `Id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `contract_main` COMMENT = '合同主表';
ALTER TABLE `contract_main` MODIFY COLUMN `Id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `contract_payment_plan` COMMENT = '合同付款计划';
ALTER TABLE `contract_payment_plan` MODIFY COLUMN `Id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `contract_payment_record` COMMENT = '合同付款记录';
ALTER TABLE `contract_payment_record` MODIFY COLUMN `Id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `contract_relation` COMMENT = '合同关联';
ALTER TABLE `contract_relation` MODIFY COLUMN `Id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `contract_stat` COMMENT = '合同统计';
ALTER TABLE `contract_stat` MODIFY COLUMN `Id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `contract_template` COMMENT = '合同模板';
ALTER TABLE `contract_template` MODIFY COLUMN `Id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `data_source_connection` COMMENT = '数据源连接';
ALTER TABLE `data_source_connection` MODIFY COLUMN `Id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `frm_category` COMMENT = '表单分类';
ALTER TABLE `frm_category` MODIFY COLUMN `Id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `frm_data` COMMENT = '表单数据';
ALTER TABLE `frm_definition` COMMENT = '表单定义';
ALTER TABLE `frm_definition` MODIFY COLUMN `Id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `kb_file` COMMENT = '知识库文件';
ALTER TABLE `kb_info` COMMENT = '知识库信息';
ALTER TABLE `kb_node_source` COMMENT = '知识库节点源';
ALTER TABLE `kb_qa_history` COMMENT = '知识库问答历史';
ALTER TABLE `page_categories` COMMENT = '页面分类';
ALTER TABLE `page_categories` MODIFY COLUMN `Id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `page_definitions` COMMENT = '页面定义';
ALTER TABLE `page_definitions` MODIFY COLUMN `Id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `pdm_ebom_documents` COMMENT = 'EBOM文档';
ALTER TABLE `pdm_ebom_items` COMMENT = 'EBOM物料';
ALTER TABLE `pdm_ebom_structure` COMMENT = 'EBOM结构';
ALTER TABLE `project_attachments` COMMENT = '项目附件';
ALTER TABLE `project_info` COMMENT = '项目信息';
ALTER TABLE `project_members` COMMENT = '项目成员';
ALTER TABLE `project_phases` COMMENT = '项目阶段';
ALTER TABLE `project_swimlanes` COMMENT = '项目泳道';
ALTER TABLE `project_task_dependencies` COMMENT = '任务依赖';
ALTER TABLE `project_tasks` COMMENT = '项目任务';
ALTER TABLE `sales_bid_analysis` COMMENT = '标书分析';
ALTER TABLE `sales_bid_analysis_log` COMMENT = '标书分析日志';
ALTER TABLE `sales_bid_analysis_run` COMMENT = '标书分析运行';
ALTER TABLE `sales_bid_chapter` COMMENT = '标书章节';
ALTER TABLE `sales_bid_project` COMMENT = '投标项目';
ALTER TABLE `sales_customer` COMMENT = '销售客户';
ALTER TABLE `sales_opportunity` COMMENT = '销售机会';
ALTER TABLE `sales_process_rule` COMMENT = '销售流程规则';
ALTER TABLE `sales_product_doc` COMMENT = '产品文档';
ALTER TABLE `sales_registrations` COMMENT = '销售报备';
ALTER TABLE `sales_script` COMMENT = '销售话术';
ALTER TABLE `sales_target` COMMENT = '销售目标';
ALTER TABLE `sys_ai_generated_content` MODIFY COLUMN `Id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `sys_anonce` COMMENT = '系统公告';
ALTER TABLE `sys_anonce` MODIFY COLUMN `Id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `sys_audit_log` COMMENT = '审计日志';
ALTER TABLE `sys_audit_log` MODIFY COLUMN `Id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `sys_audit_log` MODIFY COLUMN `UserId` bigint NULL DEFAULT NULL COMMENT '用户ID';
ALTER TABLE `sys_chat_conversation` MODIFY COLUMN `Id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `sys_chat_message` COMMENT = '聊天消息';
ALTER TABLE `sys_chat_message` MODIFY COLUMN `Id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `sys_config` COMMENT = '系统配置';
ALTER TABLE `sys_config` MODIFY COLUMN `Id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `sys_dept` COMMENT = '部门';
ALTER TABLE `sys_dept` MODIFY COLUMN `Id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `sys_dept` MODIFY COLUMN `ParentId` bigint NULL DEFAULT NULL COMMENT '父级ID';
ALTER TABLE `sys_dict_category` COMMENT = '字典分类';
ALTER TABLE `sys_dict_category` MODIFY COLUMN `Id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `sys_dict_data` COMMENT = '字典数据';
ALTER TABLE `sys_dict_data` MODIFY COLUMN `Id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `sys_dict_type` COMMENT = '字典类型';
ALTER TABLE `sys_dict_type` MODIFY COLUMN `Id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `sys_file` COMMENT = '系统文件';
ALTER TABLE `sys_file` MODIFY COLUMN `Id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `sys_file_share` COMMENT = '文件分享';
ALTER TABLE `sys_file_share` MODIFY COLUMN `Id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `sys_org_registration` COMMENT = '组织注册';
ALTER TABLE `sys_org_registration` MODIFY COLUMN `Id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `sys_permission` COMMENT = '权限';
ALTER TABLE `sys_permission` MODIFY COLUMN `Id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `sys_permission` MODIFY COLUMN `ParentId` bigint NULL DEFAULT NULL COMMENT '父级ID';
ALTER TABLE `sys_post` COMMENT = '岗位';
ALTER TABLE `sys_post` MODIFY COLUMN `Id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `sys_role` COMMENT = '角色';
ALTER TABLE `sys_role` MODIFY COLUMN `Id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `sys_role_inheritance` COMMENT = '角色继承';
ALTER TABLE `sys_role_permission` COMMENT = '角色权限';
ALTER TABLE `sys_role_permission` MODIFY COLUMN `RoleId` bigint NOT NULL COMMENT '角色ID';
ALTER TABLE `sys_user` COMMENT = '用户';
ALTER TABLE `sys_user` MODIFY COLUMN `Id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `sys_user_post` COMMENT = '用户岗位关联';
ALTER TABLE `sys_user_post` MODIFY COLUMN `UserId` bigint NOT NULL COMMENT '用户ID';
ALTER TABLE `sys_user_post` MODIFY COLUMN `PostId` bigint NOT NULL COMMENT '岗位ID';
ALTER TABLE `sys_user_post` MODIFY COLUMN `DeptId` bigint NOT NULL DEFAULT 0 COMMENT '部门ID';
ALTER TABLE `sys_user_role` COMMENT = '用户角色关联';
ALTER TABLE `sys_user_role` MODIFY COLUMN `UserId` bigint NOT NULL COMMENT '用户ID';
ALTER TABLE `sys_user_role` MODIFY COLUMN `RoleId` bigint NOT NULL COMMENT '角色ID';