CREATE TABLE IF NOT EXISTS "sys_user_config" (
  "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "UserId" BIGINT NOT NULL,
  "OrgId" BIGINT NOT NULL,
  "Key" VARCHAR(100) NOT NULL,
  "Value" TEXT,
  "Description" TEXT,
  "CreatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "UpdatedAt" TIMESTAMP DEFAULT NULL,
  CONSTRAINT "PK_sys_user_config" PRIMARY KEY ("Id"),
  CONSTRAINT "FK_sys_user_config_sys_dept_OrgId" FOREIGN KEY ("OrgId") REFERENCES "sys_dept" ("Id") ON DELETE CASCADE,
  CONSTRAINT "FK_sys_user_config_sys_user_UserId" FOREIGN KEY ("UserId") REFERENCES "sys_user" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_sys_user_config_UserId_OrgId_Key" ON "sys_user_config" ("UserId", "OrgId", "Key");
CREATE INDEX "IX_sys_user_config_OrgId" ON "sys_user_config" ("OrgId");

COMMENT ON TABLE "sys_user_config" IS '用户个性化配置表';
COMMENT ON COLUMN "sys_user_config"."Id" IS '主键ID';
COMMENT ON COLUMN "sys_user_config"."UserId" IS '用户ID';
COMMENT ON COLUMN "sys_user_config"."OrgId" IS '组织ID';
COMMENT ON COLUMN "sys_user_config"."Key" IS '配置键';
COMMENT ON COLUMN "sys_user_config"."Value" IS '配置值(JSON)';
COMMENT ON COLUMN "sys_user_config"."Description" IS '描述';
COMMENT ON COLUMN "sys_user_config"."CreatedAt" IS '创建时间';
COMMENT ON COLUMN "sys_user_config"."UpdatedAt" IS '更新时间';
