CREATE TABLE "sys_task_member" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "task_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  "join_time" timestamp(6) without time zone NOT NULL,
  CONSTRAINT "PK_sys_task_member" PRIMARY KEY ("id"),
  CONSTRAINT "FK_sys_task_member_sys_task_task_id" FOREIGN KEY ("task_id") REFERENCES "sys_task" ("Id") ON DELETE CASCADE,
  CONSTRAINT "FK_sys_task_member_sys_user_user_id" FOREIGN KEY ("user_id") REFERENCES "sys_user" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_sys_task_member_task_id" ON "sys_task_member" ("task_id");
CREATE INDEX "IX_sys_task_member_user_id" ON "sys_task_member" ("user_id");

COMMENT ON TABLE "sys_task_member" IS '任务成员表';
COMMENT ON COLUMN "sys_task_member"."id" IS '主键';
COMMENT ON COLUMN "sys_task_member"."task_id" IS '任务ID';
COMMENT ON COLUMN "sys_task_member"."user_id" IS '用户ID';
COMMENT ON COLUMN "sys_task_member"."join_time" IS '加入时间';
