-- Add FinanceSubject Table
CREATE TABLE "finance_subject" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "code" varchar(50) NOT NULL,
    "name" varchar(100) NOT NULL,
    "parent_id" bigint NULL,
    "direction" varchar(20) NOT NULL DEFAULT 'income',
    "description" varchar(200) NULL,
    "is_system" boolean NOT NULL DEFAULT false,
    "is_active" boolean NOT NULL DEFAULT true,
    "org_id" bigint NULL,
    "created_at" timestamp without time zone NOT NULL DEFAULT NOW(),
    "updated_at" timestamp without time zone NULL,
    CONSTRAINT "PK_finance_subject" PRIMARY KEY ("Id")
);
CREATE INDEX "IX_finance_subject_parent_id" ON "finance_subject" ("parent_id");
CREATE INDEX "IX_finance_subject_org_id" ON "finance_subject" ("org_id");

COMMENT ON TABLE "finance_subject" IS '财务科目表';
COMMENT ON COLUMN "finance_subject"."code" IS '科目编码';
COMMENT ON COLUMN "finance_subject"."name" IS '科目名称';

-- Add FinanceApAr Table
CREATE TABLE "finance_apar" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "bill_no" varchar(50) NOT NULL,
    "type" varchar(10) NOT NULL DEFAULT 'AR',
    "subject_id" bigint NULL,
    "amount" decimal(18,2) NOT NULL,
    "due_date" timestamp without time zone NOT NULL,
    "partner_name" varchar(200) NOT NULL,
    "status" integer NOT NULL DEFAULT 0,
    "source_type" varchar(20) NULL DEFAULT 'Manual',
    "source_id" bigint NULL,
    "source_sub_id" bigint NULL,
    "description" varchar(500) NULL,
    "files" text NULL,
    "org_id" bigint NULL,
    "created_at" timestamp without time zone NOT NULL DEFAULT NOW(),
    "updated_at" timestamp without time zone NULL,
    "created_by" varchar(50) NULL,
    CONSTRAINT "PK_finance_apar" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_finance_apar_subject" FOREIGN KEY ("subject_id") REFERENCES "finance_subject" ("Id")
);
CREATE INDEX "IX_finance_apar_subject_id" ON "finance_apar" ("subject_id");
CREATE INDEX "IX_finance_apar_org_id" ON "finance_apar" ("org_id");

COMMENT ON TABLE "finance_apar" IS '应收应付账款表';

-- Add FinanceAttachment Table
CREATE TABLE "finance_attachment" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "target_type" varchar(50) NOT NULL,
    "target_id" bigint NOT NULL,
    "file_name" varchar(200) NOT NULL,
    "file_path" varchar(500) NULL,
    "size" varchar(20) NULL,
    "content_type" varchar(100) NULL,
    "upload_date" timestamp without time zone NOT NULL DEFAULT NOW(),
    "uploader" varchar(50) NULL,
    CONSTRAINT "PK_finance_attachment" PRIMARY KEY ("Id")
);
CREATE INDEX "IX_finance_attachment_target" ON "finance_attachment" ("target_type", "target_id");

-- Seed Initial Finance Subjects
INSERT INTO "finance_subject" ("code", "name", "direction", "is_system", "description", "created_at") VALUES
('1001', '合同款', 'income', false, '合同销售回款', NOW()),
('2001', '合同付款', 'expense', false, '合同采购付款', NOW()),
('1002', '其他收入', 'income', false, '非主营业务收入', NOW()),
('2002', '日常报销', 'expense', false, '日常费用报销', NOW());
