CREATE TABLE "sys_task_attachment" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "task_id" bigint NOT NULL,
  "file_name" varchar(255) NOT NULL,
  "file_path" varchar(500) NOT NULL,
  "extension" varchar(20) NULL,
  "file_size" bigint NOT NULL,
  "content_type" varchar(100) NULL,
  "uploader_id" bigint NOT NULL,
  "create_time" timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PK_sys_task_attachment" PRIMARY KEY ("id"),
  CONSTRAINT "FK_sys_task_attachment_sys_task_task_id" FOREIGN KEY ("task_id") REFERENCES "sys_task" ("Id") ON DELETE CASCADE,
  CONSTRAINT "FK_sys_task_attachment_sys_user_uploader_id" FOREIGN KEY ("uploader_id") REFERENCES "sys_user" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_sys_task_attachment_task_id" ON "sys_task_attachment" ("task_id");
CREATE INDEX "IX_sys_task_attachment_uploader_id" ON "sys_task_attachment" ("uploader_id");

COMMENT ON TABLE "sys_task_attachment" IS '任务附件';
COMMENT ON COLUMN "sys_task_attachment"."task_id" IS '任务ID';
COMMENT ON COLUMN "sys_task_attachment"."file_name" IS '文件名';
COMMENT ON COLUMN "sys_task_attachment"."file_path" IS '文件路径';
COMMENT ON COLUMN "sys_task_attachment"."extension" IS '扩展名';
COMMENT ON COLUMN "sys_task_attachment"."file_size" IS '文件大小';
COMMENT ON COLUMN "sys_task_attachment"."content_type" IS '文件类型';
COMMENT ON COLUMN "sys_task_attachment"."uploader_id" IS '上传者ID';
COMMENT ON COLUMN "sys_task_attachment"."create_time" IS '创建时间';
