CREATE TABLE "sys_task" (
  "Id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "title" varchar(200) NOT NULL,
  "type" varchar(50) NOT NULL DEFAULT 'task',
  "priority" varchar(20) NOT NULL DEFAULT 'medium',
  "description" text NULL,
  "creator_id" bigint NOT NULL,
  "assignee_id" bigint NOT NULL,
  "create_time" timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deadline" timestamp(6) without time zone NULL,
  "finish_time" timestamp(6) without time zone NULL,
  "status" varchar(50) NOT NULL DEFAULT 'pending',
  "org_id" bigint NOT NULL DEFAULT 0,
  CONSTRAINT "PK_sys_task" PRIMARY KEY ("Id"),
  CONSTRAINT "FK_sys_task_sys_user_creator_id" FOREIGN KEY ("creator_id") REFERENCES "sys_user" ("Id") ON DELETE CASCADE,
  CONSTRAINT "FK_sys_task_sys_user_assignee_id" FOREIGN KEY ("assignee_id") REFERENCES "sys_user" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_sys_task_creator_id" ON "sys_task" ("creator_id");
CREATE INDEX "IX_sys_task_assignee_id" ON "sys_task" ("assignee_id");
CREATE INDEX "IX_sys_task_org_id" ON "sys_task" ("org_id");

COMMENT ON TABLE "sys_task" IS '个人待办任务表';
COMMENT ON COLUMN "sys_task"."title" IS '任务标题';
COMMENT ON COLUMN "sys_task"."type" IS '类型：task, approval, notice';
COMMENT ON COLUMN "sys_task"."priority" IS '优先级：high, medium, low';
COMMENT ON COLUMN "sys_task"."description" IS '任务描述';
COMMENT ON COLUMN "sys_task"."creator_id" IS '创建人ID';
COMMENT ON COLUMN "sys_task"."assignee_id" IS '执行人ID';
COMMENT ON COLUMN "sys_task"."create_time" IS '创建时间';
COMMENT ON COLUMN "sys_task"."deadline" IS '截止时间';
COMMENT ON COLUMN "sys_task"."finish_time" IS '完成时间';
COMMENT ON COLUMN "sys_task"."status" IS '状态：pending, completed';
COMMENT ON COLUMN "sys_task"."org_id" IS '组织ID';
