CREATE TABLE "sys_task_process" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "task_id" bigint NOT NULL,
  "operator_id" bigint NOT NULL,
  "action" varchar(50) NOT NULL DEFAULT 'process',
  "comment" text NULL,
  "create_time" timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "attachment_ids" varchar(500) NULL,
  CONSTRAINT "PK_sys_task_process" PRIMARY KEY ("id"),
  CONSTRAINT "FK_sys_task_process_sys_task_task_id" FOREIGN KEY ("task_id") REFERENCES "sys_task" ("Id") ON DELETE CASCADE,
  CONSTRAINT "FK_sys_task_process_sys_user_operator_id" FOREIGN KEY ("operator_id") REFERENCES "sys_user" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_sys_task_process_task_id" ON "sys_task_process" ("task_id");
CREATE INDEX "IX_sys_task_process_operator_id" ON "sys_task_process" ("operator_id");

COMMENT ON TABLE "sys_task_process" IS '任务处理记录';
COMMENT ON COLUMN "sys_task_process"."task_id" IS '任务ID';
COMMENT ON COLUMN "sys_task_process"."operator_id" IS '操作人ID';
COMMENT ON COLUMN "sys_task_process"."action" IS '操作类型';
COMMENT ON COLUMN "sys_task_process"."comment" IS '处理意见';
COMMENT ON COLUMN "sys_task_process"."create_time" IS '创建时间';
COMMENT ON COLUMN "sys_task_process"."attachment_ids" IS '附件ID列表';
