// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using omsapi.Data;

#nullable disable

namespace omsapi.Migrations
{
    [DbContext(typeof(OmsContext))]
    partial class OmsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("omsapi.Models.Entities.Archive.ArchAttachment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ArchFileId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Extension")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<long?>("FileId")
                        .HasColumnType("bigint");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ArchFileId");

                    b.HasIndex("FileId");

                    b.ToTable("arch_attachment");
                });

            modelBuilder.Entity("omsapi.Models.Entities.Archive.ArchBox", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BoxCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FileCount")
                        .HasColumnType("int");

                    b.Property<long>("FondId")
                        .HasColumnType("bigint");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("RFID")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Remark")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("RetentionPeriod")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("SecurityLevel")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<long>("TypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Year")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("BoxCode")
                        .IsUnique();

                    b.HasIndex("FondId");

                    b.HasIndex("TypeId");

                    b.ToTable("arch_box");
                });

            modelBuilder.Entity("omsapi.Models.Entities.Archive.ArchFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ArchCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Author")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<long?>("BoxId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DocNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("FileDate")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("FondId")
                        .HasColumnType("bigint");

                    b.Property<string>("Keywords")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("RetentionPeriod")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("SecurityLevel")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<long?>("SourceFileId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<long>("TypeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Year")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("ArchCode")
                        .IsUnique();

                    b.HasIndex("BoxId");

                    b.HasIndex("FondId");

                    b.HasIndex("TypeId");

                    b.ToTable("arch_file");
                });

            modelBuilder.Entity("omsapi.Models.Entities.Archive.ArchFond", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("arch_fond");
                });

            modelBuilder.Entity("omsapi.Models.Entities.Archive.ArchType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("arch_type");
                });

            modelBuilder.Entity("omsapi.Models.Entities.BigView.BigViewProject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("longtext")
                        .HasColumnName("content");

                    b.Property<string>("CreateBy")
                        .HasColumnType("longtext")
                        .HasColumnName("create_by");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_time");

                    b.Property<string>("IndexImage")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("index_image");

                    b.Property<string>("IsDelete")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("is_delete");

                    b.Property<string>("ProjectName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("project_name");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("remarks");

                    b.Property<string>("State")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.ToTable("bigview_project");
                });

            modelBuilder.Entity("omsapi.Models.Entities.Data.DataSourceConnection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Database")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Port")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("data_source_connection");
                });

            modelBuilder.Entity("omsapi.Models.Entities.Forms.FormCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("frm_category");
                });

            modelBuilder.Entity("omsapi.Models.Entities.Forms.FormDefinition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("FormItems")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LimitOnePerUser")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("RequiresLogin")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("frm_definition");
                });

            modelBuilder.Entity("omsapi.Models.Entities.Forms.FormResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("data");

                    b.Property<long>("FormId")
                        .HasColumnType("bigint")
                        .HasColumnName("form_id");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("submitted_at");

                    b.Property<string>("SubmittedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("submitted_by");

                    b.HasKey("Id");

                    b.ToTable("frm_data");
                });

            modelBuilder.Entity("omsapi.Models.Entities.SystemAuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("longtext");

                    b.Property<long>("ExecutionDuration")
                        .HasColumnType("bigint");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Method")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Parameters")
                        .HasColumnType("longtext");

                    b.Property<string>("Route")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("sys_audit_log");
                });

            modelBuilder.Entity("omsapi.Models.Entities.SystemConfig", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Value")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("sys_config");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Category = "Basic",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "系统名称",
                            IsSystem = true,
                            Key = "SystemName",
                            Value = "金兰®综合信息管理系统"
                        },
                        new
                        {
                            Id = 2L,
                            Category = "Basic",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "系统Logo路径",
                            IsSystem = true,
                            Key = "SystemLogo",
                            Value = "/logo.svg"
                        },
                        new
                        {
                            Id = 3L,
                            Category = "Basic",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "底部版权信息",
                            IsSystem = true,
                            Key = "Copyright",
                            Value = "©2025 Created by jinlan.info"
                        },
                        new
                        {
                            Id = 4L,
                            Category = "Security",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "密码最小长度",
                            IsSystem = true,
                            Key = "PasswordMinLength",
                            Value = "6"
                        },
                        new
                        {
                            Id = 5L,
                            Category = "Security",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "会话超时时间(分钟)",
                            IsSystem = true,
                            Key = "SessionTimeout",
                            Value = "30"
                        });
                });

            modelBuilder.Entity("omsapi.Models.Entities.SystemDept", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Leader")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<double?>("X")
                        .HasColumnType("double");

                    b.Property<double?>("Y")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("sys_dept");
                });

            modelBuilder.Entity("omsapi.Models.Entities.SystemFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ContentType")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("DeptId")
                        .HasColumnType("bigint");

                    b.Property<string>("Extension")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsFolder")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DeptId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ParentId");

                    b.ToTable("sys_file");
                });

            modelBuilder.Entity("omsapi.Models.Entities.SystemFileShare", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("FileId")
                        .HasColumnType("bigint");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<long>("SharedByUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SharedToUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Token")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.HasIndex("SharedByUserId");

                    b.HasIndex("SharedToUserId");

                    b.ToTable("sys_file_share");
                });

            modelBuilder.Entity("omsapi.Models.Entities.SystemPermission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Component")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Path")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Query")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("sys_permission");

                    b.HasData(
                        new
                        {
                            Id = 102L,
                            Code = "archive:fond:view",
                            CreatedAt = new DateTime(2025, 12, 22, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsVisible = false,
                            Name = "全宗查看",
                            ParentId = 47L,
                            SortOrder = 1,
                            Type = "BUTTON"
                        },
                        new
                        {
                            Id = 103L,
                            Code = "archive:fond:add",
                            CreatedAt = new DateTime(2025, 12, 22, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsVisible = false,
                            Name = "全宗新增",
                            ParentId = 47L,
                            SortOrder = 2,
                            Type = "BUTTON"
                        },
                        new
                        {
                            Id = 104L,
                            Code = "archive:fond:edit",
                            CreatedAt = new DateTime(2025, 12, 22, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsVisible = false,
                            Name = "全宗编辑",
                            ParentId = 47L,
                            SortOrder = 3,
                            Type = "BUTTON"
                        },
                        new
                        {
                            Id = 105L,
                            Code = "archive:fond:delete",
                            CreatedAt = new DateTime(2025, 12, 22, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsVisible = false,
                            Name = "全宗删除",
                            ParentId = 47L,
                            SortOrder = 4,
                            Type = "BUTTON"
                        },
                        new
                        {
                            Id = 108L,
                            Code = "archive:file:view",
                            CreatedAt = new DateTime(2025, 12, 22, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsVisible = false,
                            Name = "档案查看",
                            ParentId = 47L,
                            SortOrder = 5,
                            Type = "BUTTON"
                        },
                        new
                        {
                            Id = 109L,
                            Code = "archive:file:add",
                            CreatedAt = new DateTime(2025, 12, 22, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsVisible = false,
                            Name = "档案新增",
                            ParentId = 47L,
                            SortOrder = 6,
                            Type = "BUTTON"
                        },
                        new
                        {
                            Id = 110L,
                            Code = "archive:file:edit",
                            CreatedAt = new DateTime(2025, 12, 22, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsVisible = false,
                            Name = "档案编辑",
                            ParentId = 47L,
                            SortOrder = 7,
                            Type = "BUTTON"
                        },
                        new
                        {
                            Id = 111L,
                            Code = "archive:file:delete",
                            CreatedAt = new DateTime(2025, 12, 22, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsVisible = false,
                            Name = "档案删除",
                            ParentId = 47L,
                            SortOrder = 8,
                            Type = "BUTTON"
                        },
                        new
                        {
                            Id = 106L,
                            Code = "archive:type:view",
                            CreatedAt = new DateTime(2025, 12, 22, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsVisible = false,
                            Name = "分类查看",
                            ParentId = 74L,
                            SortOrder = 1,
                            Type = "BUTTON"
                        },
                        new
                        {
                            Id = 107L,
                            Code = "archive:type:add",
                            CreatedAt = new DateTime(2025, 12, 22, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsVisible = false,
                            Name = "分类新增",
                            ParentId = 74L,
                            SortOrder = 2,
                            Type = "BUTTON"
                        },
                        new
                        {
                            Id = 112L,
                            Code = "archive:type:edit",
                            CreatedAt = new DateTime(2025, 12, 22, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsVisible = false,
                            Name = "分类编辑",
                            ParentId = 74L,
                            SortOrder = 3,
                            Type = "BUTTON"
                        },
                        new
                        {
                            Id = 113L,
                            Code = "archive:type:delete",
                            CreatedAt = new DateTime(2025, 12, 22, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsVisible = false,
                            Name = "分类删除",
                            ParentId = 74L,
                            SortOrder = 4,
                            Type = "BUTTON"
                        });
                });

            modelBuilder.Entity("omsapi.Models.Entities.SystemPost", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("DeptId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Remark")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DeptId");

                    b.ToTable("sys_post");
                });

            modelBuilder.Entity("omsapi.Models.Entities.SystemRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("DeptId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DeptId");

                    b.ToTable("sys_role");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "ADMIN",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "系统最高权限",
                            IsSystem = true,
                            Name = "超级管理员"
                        });
                });

            modelBuilder.Entity("omsapi.Models.Entities.SystemRoleInheritance", b =>
                {
                    b.Property<long>("ParentRoleId")
                        .HasColumnType("bigint");

                    b.Property<long>("ChildRoleId")
                        .HasColumnType("bigint");

                    b.HasKey("ParentRoleId", "ChildRoleId");

                    b.HasIndex("ChildRoleId");

                    b.ToTable("sys_role_inheritance");
                });

            modelBuilder.Entity("omsapi.Models.Entities.SystemRolePermission", b =>
                {
                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<long>("PermissionId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("RoleId", "PermissionId");

                    b.ToTable("sys_role_permission");

                    b.HasData(
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 102L,
                            CreatedAt = new DateTime(2025, 12, 22, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 103L,
                            CreatedAt = new DateTime(2025, 12, 22, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 104L,
                            CreatedAt = new DateTime(2025, 12, 22, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 105L,
                            CreatedAt = new DateTime(2025, 12, 22, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 106L,
                            CreatedAt = new DateTime(2025, 12, 22, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 107L,
                            CreatedAt = new DateTime(2025, 12, 22, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 112L,
                            CreatedAt = new DateTime(2025, 12, 22, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 113L,
                            CreatedAt = new DateTime(2025, 12, 22, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 108L,
                            CreatedAt = new DateTime(2025, 12, 22, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 109L,
                            CreatedAt = new DateTime(2025, 12, 22, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 110L,
                            CreatedAt = new DateTime(2025, 12, 22, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 111L,
                            CreatedAt = new DateTime(2025, 12, 22, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("omsapi.Models.Entities.SystemUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Avatar")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("DeptId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nickname")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DeptId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("sys_user");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Nickname = "超级管理员",
                            Password = "240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9",
                            Status = "online",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("omsapi.Models.Entities.SystemUserPost", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("PostId")
                        .HasColumnType("bigint");

                    b.Property<long>("DeptId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "PostId", "DeptId");

                    b.HasIndex("DeptId");

                    b.HasIndex("PostId");

                    b.ToTable("sys_user_post");
                });

            modelBuilder.Entity("omsapi.Models.Entities.SystemUserRole", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("sys_user_role");

                    b.HasData(
                        new
                        {
                            UserId = 1L,
                            RoleId = 1L,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("omsapi.Models.Entities.Archive.ArchAttachment", b =>
                {
                    b.HasOne("omsapi.Models.Entities.Archive.ArchFile", "ArchFile")
                        .WithMany("Attachments")
                        .HasForeignKey("ArchFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("omsapi.Models.Entities.SystemFile", "File")
                        .WithMany()
                        .HasForeignKey("FileId");

                    b.Navigation("ArchFile");

                    b.Navigation("File");
                });

            modelBuilder.Entity("omsapi.Models.Entities.Archive.ArchBox", b =>
                {
                    b.HasOne("omsapi.Models.Entities.Archive.ArchFond", "Fond")
                        .WithMany()
                        .HasForeignKey("FondId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("omsapi.Models.Entities.Archive.ArchType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fond");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("omsapi.Models.Entities.Archive.ArchFile", b =>
                {
                    b.HasOne("omsapi.Models.Entities.Archive.ArchBox", "Box")
                        .WithMany()
                        .HasForeignKey("BoxId");

                    b.HasOne("omsapi.Models.Entities.Archive.ArchFond", "Fond")
                        .WithMany()
                        .HasForeignKey("FondId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("omsapi.Models.Entities.Archive.ArchType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Box");

                    b.Navigation("Fond");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("omsapi.Models.Entities.Archive.ArchType", b =>
                {
                    b.HasOne("omsapi.Models.Entities.Archive.ArchType", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("omsapi.Models.Entities.Forms.FormCategory", b =>
                {
                    b.HasOne("omsapi.Models.Entities.Forms.FormCategory", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("omsapi.Models.Entities.Forms.FormDefinition", b =>
                {
                    b.HasOne("omsapi.Models.Entities.Forms.FormCategory", "Category")
                        .WithMany("Forms")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("omsapi.Models.Entities.SystemDept", b =>
                {
                    b.HasOne("omsapi.Models.Entities.SystemDept", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("omsapi.Models.Entities.SystemFile", b =>
                {
                    b.HasOne("omsapi.Models.Entities.SystemDept", "Dept")
                        .WithMany()
                        .HasForeignKey("DeptId");

                    b.HasOne("omsapi.Models.Entities.SystemUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("omsapi.Models.Entities.SystemFile", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Dept");

                    b.Navigation("Owner");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("omsapi.Models.Entities.SystemFileShare", b =>
                {
                    b.HasOne("omsapi.Models.Entities.SystemFile", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("omsapi.Models.Entities.SystemUser", "SharedByUser")
                        .WithMany()
                        .HasForeignKey("SharedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("omsapi.Models.Entities.SystemUser", "SharedToUser")
                        .WithMany()
                        .HasForeignKey("SharedToUserId");

                    b.Navigation("File");

                    b.Navigation("SharedByUser");

                    b.Navigation("SharedToUser");
                });

            modelBuilder.Entity("omsapi.Models.Entities.SystemPost", b =>
                {
                    b.HasOne("omsapi.Models.Entities.SystemDept", "Dept")
                        .WithMany()
                        .HasForeignKey("DeptId");

                    b.Navigation("Dept");
                });

            modelBuilder.Entity("omsapi.Models.Entities.SystemRole", b =>
                {
                    b.HasOne("omsapi.Models.Entities.SystemDept", "Dept")
                        .WithMany()
                        .HasForeignKey("DeptId");

                    b.Navigation("Dept");
                });

            modelBuilder.Entity("omsapi.Models.Entities.SystemRoleInheritance", b =>
                {
                    b.HasOne("omsapi.Models.Entities.SystemRole", "ChildRole")
                        .WithMany("ParentRoleRelations")
                        .HasForeignKey("ChildRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("omsapi.Models.Entities.SystemRole", "ParentRole")
                        .WithMany("ChildRoleRelations")
                        .HasForeignKey("ParentRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChildRole");

                    b.Navigation("ParentRole");
                });

            modelBuilder.Entity("omsapi.Models.Entities.SystemUser", b =>
                {
                    b.HasOne("omsapi.Models.Entities.SystemDept", "Dept")
                        .WithMany("Users")
                        .HasForeignKey("DeptId");

                    b.Navigation("Dept");
                });

            modelBuilder.Entity("omsapi.Models.Entities.SystemUserPost", b =>
                {
                    b.HasOne("omsapi.Models.Entities.SystemDept", "Dept")
                        .WithMany()
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("omsapi.Models.Entities.SystemPost", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("omsapi.Models.Entities.SystemUser", "User")
                        .WithMany("UserPosts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dept");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("omsapi.Models.Entities.SystemUserRole", b =>
                {
                    b.HasOne("omsapi.Models.Entities.SystemRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("omsapi.Models.Entities.SystemUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("omsapi.Models.Entities.Archive.ArchFile", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("omsapi.Models.Entities.Archive.ArchType", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("omsapi.Models.Entities.Forms.FormCategory", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Forms");
                });

            modelBuilder.Entity("omsapi.Models.Entities.SystemDept", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("omsapi.Models.Entities.SystemFile", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("omsapi.Models.Entities.SystemRole", b =>
                {
                    b.Navigation("ChildRoleRelations");

                    b.Navigation("ParentRoleRelations");
                });

            modelBuilder.Entity("omsapi.Models.Entities.SystemUser", b =>
                {
                    b.Navigation("UserPosts");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
